[render]
max_sample_count = 50
max_depth = 5

[film]
aspect_ratio = 1.0
width = 1280
height = 720
background = [0.53, 0.80, 0.92]

[camera]
position = [0.0, 0.0, 3.0]
look_at = [0.0, 0.0, 0.0]
fov = 45.0
aperature = 0.0
focus_distance = 10.0

[[materials]]
name = "Test"

[[shapes]]
name = "Sphere"
properties = { radius = 0.25 }

[[shapes]]
name = "Sphere"
translate = [1.5, 0.0, 0.0]
properties = { radius = 0.25, phi_max = 180.0 }

[[primitives]]
name = "Geometric"
shape = 0
material = 0

[[primitives]]
name = "Geometric"
shape = 1
material = 0
