[package]
name = "pat"
version = "0.1.0"
authors = ["Kazi Jawad"]
edition = "2021"

[features]
float-as-double = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "0.1"
rand = "0.8.5"
rayon = "1.6.0"
image = "0.24.5"
